import { test, before, after, beforeEach } from "node:test";
import assert from "node:assert/strict";

import type { PGlite } from "@electric-sql/pglite";

import { makeTestDb, type TestDb } from "../db/test-harness";
import { __setTestDb, __resetTestDb } from "../db/client";
import { runWithIdentity } from "../auth/request-context";
import { __setAgentConnectorForTest } from "../infra/agent-client";
import { seedIdentity, TEAM_A, USER_1 } from "./identity-test-helpers";
import {
  seedApp,
  seedServer,
  SERVER_1,
  TRUNCATE_PROJECT_GRAPH,
} from "./app-graph-test-helpers";
import { seedRun, seedS3, TRUNCATE_BACKUPS } from "./backup-test-helpers";
import {
  environments as environmentsTable,
  projects as projectsTable,
} from "../db/schema/control-plane";
import { restoreBackup } from "./backups";

/**
 * A restore ends in the agent's own Reroute, and the agent prefers the compose
 * inside the ARCHIVE - which names the network the app had when the backup ran.
 * https://deplo.build/docs/advanced/network-isolation
 */

let db: TestDb;
let pg: PGlite;
let calls: { m: string; args: unknown[] }[] = [];

const T0 = "2026-01-01T00:00:00.000Z";

before(async () => {
  ({ db, pg } = await makeTestDb());
  __setTestDb(db);
  __setAgentConnectorForTest(
    async () =>
      new Proxy(
        {},
        {
          get(_t, prop: string) {
            if (prop === "close") return () => {};
            if (prop === "then") return undefined;
            if (prop === "restore" || prop === "restoreFrom")
              return (...args: unknown[]) => {
                calls.push({ m: prop, args });
                return (async function* () {
                  yield { result: { ok: true, error: "" } };
                })();
              };
            return async (...args: unknown[]) => {
              calls.push({ m: prop, args });
              if (prop === "hello")
                return {
                  ok: true,
                  capabilities: [
                    "backup",
                    "backup-store",
                    "backup-encrypt-s3",
                    "backup-s3-args",
                    "deploy.network",
                  ],
                };
              return {
                ok: true,
                exists: true,
                yaml: "# Generated by Deplo  a\nservices:\n  web:\n    image: i\n",
                error: "",
              };
            };
          },
        },
      ) as never,
  );
});

after(async () => {
  __setAgentConnectorForTest();
  __resetTestDb();
  await pg.close();
});

beforeEach(async () => {
  await pg.exec(`${TRUNCATE_BACKUPS}${TRUNCATE_PROJECT_GRAPH}
    truncate table users, teams restart identity cascade;`);
  await seedIdentity(db, {
    users: [{ id: USER_1, teamId: TEAM_A, role: "owner" }],
  });
  await seedServer(db);
  // A provisioned host: the backup path refuses one whose agent never called home.
  await db.execute(
    `update servers set agent_cert_fingerprint = 'sha256:pinned',
       agent_cert_pem = 'x', agent_port = 9443, agent_version = '1.31.0'
     where id = '${SERVER_1}'`,
  );
  await db.insert(projectsTable).values({
    id: "prc_1",
    teamId: TEAM_A,
    name: "Shop",
    slug: "shop",
    position: 0,
    createdAt: T0,
    updatedAt: T0,
  } as never);
  await db.insert(environmentsTable).values({
    id: "environ_prod",
    projectId: "prc_1",
    name: "Production",
    slug: "production",
    kind: "production",
    isDefault: true,
    position: 0,
    createdAt: T0,
    updatedAt: T0,
  } as never);
  calls = [];
});

test("a restored app is put back on the network it lives on TODAY", async () => {
  await seedApp(db, {
    id: "prj_a",
    slug: "a",
    source: "compose",
    compose: "services:\n  web:\n    image: i\n",
    projectId: "prc_1",
    environmentId: "environ_prod",
  });
  const dest = await seedS3(db, { id: "dst_1" });
  await seedRun(db, {
    id: "run_1",
    destinationId: dest,
    targetKind: "app",
    appId: "prj_a",
    status: "success",
  });

  await runWithIdentity({ userId: USER_1, teamId: TEAM_A }, () =>
    restoreBackup("run_1"),
  );

  const reroutes = calls.filter((c) => c.m === "reroute");
  assert.equal(reroutes.length, 1, "the restore re-renders the stack");
  assert.equal(
    (reroutes[0]!.args[0] as { network: string }).network,
    "deplo-env-environ_prod",
    "on the app's CURRENT environment, not the archive's",
  );
});

test("a failed restore does not reroute", async () => {
  await seedApp(db, {
    id: "prj_a",
    slug: "a",
    source: "compose",
    compose: "services:\n  web:\n    image: i\n",
    projectId: "prc_1",
    environmentId: "environ_prod",
  });
  const dest = await seedS3(db, { id: "dst_1" });
  await seedRun(db, {
    id: "run_1",
    destinationId: dest,
    targetKind: "app",
    appId: "prj_a",
    status: "failed",
  });

  await assert.rejects(() =>
    runWithIdentity({ userId: USER_1, teamId: TEAM_A }, () =>
      restoreBackup("run_1"),
    ),
  );
  assert.equal(calls.filter((c) => c.m === "reroute").length, 0);
});
