import "server-only";

import { mkdtemp, mkdir, rm, writeFile, access } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { read, mutate } from "../store";
import { newId, nowIso } from "../ids";
import { decryptSecret } from "../crypto";
import { recordActivity } from "../data/activity";
import { docker, ensureNetwork } from "../infra/docker";
import { spawnStream } from "../infra/exec";
import { cloneStream, revParse } from "../infra/git";
import { generateDockerfile } from "./dockerfile";
import { productionDomain, previewDomain, instanceHost } from "./domains";
import type { Deployment, DeploymentEnvironment, LogLine, Server } from "../types";

const DATA_DIR = process.env.DEPLO_DATA_DIR || "/data";
const STACK_DIR = join(DATA_DIR, "stacks");

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function serverIp(server: Server | undefined): string {
  if (!server || server.type === "localhost") return instanceHost();
  return server.ip || instanceHost();
}

function log(depId: string, level: LogLine["level"], text: string): void {
  mutate((d) => {
    (d.logs[depId] ??= []).push({ ts: nowIso(), level, text });
  });
}

function setDep(depId: string, patch: Partial<Deployment>): void {
  mutate((d) => {
    const x = d.deployments.find((y) => y.id === depId);
    if (x) Object.assign(x, patch);
  });
}

function setProject(projectId: string, patch: Record<string, unknown>): void {
  mutate((d) => {
    const p = d.projects.find((x) => x.id === projectId);
    if (p) Object.assign(p, patch, { updatedAt: nowIso() });
  });
}

/** Decrypted env (project vars targeting production + attached shared groups). */
function projectEnv(projectId: string): Record<string, string> {
  const d = read();
  const out: Record<string, string> = {};
  for (const e of d.envVars) {
    if (e.projectId === projectId && e.targets.includes("production")) {
      out[e.key] = decryptSecret(e.valueEnc);
    }
  }
  for (const g of d.sharedEnvGroups ?? []) {
    if (g.projectIds.includes(projectId)) {
      for (const v of g.variables) out[v.key] = decryptSecret(v.valueEnc);
    }
  }
  return out;
}

function renderCompose(opts: {
  name: string;
  image: string;
  port: number;
  projectId: string;
  slug: string;
  domain: string;
  env: Record<string, string>;
}): string {
  const { name, image, port, projectId, slug, domain, env } = opts;
  // Traefik routing (TLS via Let's Encrypt). The global web->websecure redirect
  // is configured on the proxy, so no per-router middleware is needed here.
  const labels = [
    "traefik.enable=true",
    `traefik.http.routers.${name}.rule=Host(\`${domain}\`)`,
    `traefik.http.routers.${name}.entrypoints=websecure`,
    `traefik.http.routers.${name}.tls=true`,
    `traefik.http.routers.${name}.tls.certresolver=letsencrypt`,
    `traefik.http.services.${name}.loadbalancer.server.port=${port}`,
    "deplo.managed=true",
    `deplo.project=${projectId}`,
    `deplo.slug=${slug}`,
  ];
  const labelsYaml = labels.map((l) => `      - "${l}"`).join("\n");
  const envYaml = Object.keys(env).length
    ? "    environment:\n" +
      Object.entries(env)
        .map(([k, v]) => `      ${k}: ${JSON.stringify(v)}`)
        .join("\n") +
      "\n"
    : "";

  return `# Generated by Deplo  ${slug}
services:
  ${name}:
    image: ${image}
    container_name: ${name}
    restart: unless-stopped
    networks:
      - deplo
${envYaml}    labels:
${labelsYaml}

networks:
  deplo:
    external: true
`;
}

async function streamDocker(
  args: string[],
  depId: string,
  timeout: number,
): Promise<void> {
  const code = await spawnStream(
    "docker",
    args,
    (line) => log(depId, "info", line),
    { timeout },
  );
  if (code !== 0) throw new Error(`docker ${args[0]} failed (exit ${code})`);
}

async function waitRunning(name: string, ms: number): Promise<boolean> {
  const deadline = Date.now() + ms;
  while (Date.now() < deadline) {
    try {
      const { stdout } = await docker(
        ["inspect", "-f", "{{.State.Running}}", name],
        { timeout: 5_000 },
      );
      if (stdout.trim() === "true") return true;
    } catch {
      /* not up yet */
    }
    await sleep(2_000);
  }
  return false;
}

async function fileExists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * Create a deployment record (queued) and kick off the real build in the
 * background. Returns the deployment id immediately; the job updates status and
 * logs as it progresses.
 */
export function startDeployment(
  projectId: string,
  opts: {
    environment?: DeploymentEnvironment;
    creator: string;
    commitMessage?: string;
    branch?: string;
  },
): string {
  const project = read().projects.find((p) => p.id === projectId);
  if (!project) throw new Error("Project not found");
  const server = read().servers.find((s) => s.id === project.serverId);
  const ip = serverIp(server);
  const environment = opts.environment ?? "production";
  const branch = opts.branch ?? project.repo?.branch ?? "main";
  const domain =
    environment === "production"
      ? productionDomain(project.slug, ip)
      : previewDomain(project.slug, newId("").slice(1, 7), ip);
  const url = `https://${domain}`;
  const depId = newId("dpl");

  const dep: Deployment = {
    id: depId,
    projectId,
    status: "queued",
    environment,
    commitSha: "",
    commitMessage: opts.commitMessage ?? "Deploy",
    commitAuthor: opts.creator,
    branch,
    url,
    createdAt: nowIso(),
    readyAt: null,
    buildDurationMs: null,
    creator: opts.creator,
  };

  mutate((d) => {
    d.deployments.push(dep);
    d.logs[depId] = [];
    const p = d.projects.find((x) => x.id === projectId);
    if (p) {
      p.latestDeploymentId = depId;
      p.status = "queued";
      p.updatedAt = nowIso();
      if (environment === "production") p.productionUrl = url;
    }
  });
  recordActivity("deployment", `Deploying ${project.name}`, opts.creator, projectId);

  // Fire-and-forget: the standalone Node server keeps the event loop alive.
  void runDeployment(depId).catch((e) => {
    log(depId, "error", e instanceof Error ? e.message : String(e));
    setDep(depId, { status: "error" });
  });
  return depId;
}

async function runDeployment(depId: string): Promise<void> {
  const started = Date.now();
  const dep = read().deployments.find((x) => x.id === depId);
  if (!dep) return;
  const project = read().projects.find((p) => p.id === dep.projectId);
  if (!project) {
    setDep(depId, { status: "error" });
    return;
  }
  const slug = project.slug;
  const name = `deplo-${slug}`;
  const stackFile = join(STACK_DIR, `${slug}.yml`);
  const server = read().servers.find((s) => s.id === project.serverId);
  const ip = serverIp(server);
  const domain =
    dep.environment === "production"
      ? productionDomain(slug, ip)
      : dep.url.replace(/^https?:\/\//, "");

  setDep(depId, { status: "building" });
  setProject(project.id, { status: "building" });

  try {
    await mkdir(STACK_DIR, { recursive: true });
    await ensureNetwork("deplo");

    let imageRef: string;
    let commitSha = "";

    if (project.source === "docker-image" && project.dockerImage) {
      log(depId, "command", `docker pull ${project.dockerImage}`);
      await streamDocker(["pull", project.dockerImage], depId, 600_000);
      imageRef = project.dockerImage;
    } else if (project.repo) {
      const work = await mkdtemp(join(tmpdir(), "deplo-build-"));
      try {
        log(depId, "command", `git clone ${project.repo.url} (${dep.branch})`);
        await cloneStream(project.repo.url, dep.branch, work, (line) =>
          log(depId, "info", line),
        );
        commitSha = await revParse(work);
        if (commitSha) setDep(depId, { commitSha });

        // Resolve the build dir, guarding against `..` escaping the clone.
        const rootRel = (project.build.rootDirectory || ".")
          .replace(/\\/g, "/")
          .replace(/^\.?\/?/, "");
        const candidate =
          rootRel && rootRel !== "." ? join(work, rootRel) : work;
        const buildDir = candidate.startsWith(work) ? candidate : work;

        if (!(await fileExists(join(buildDir, "Dockerfile")))) {
          log(
            depId,
            "info",
            "No Dockerfile found  generating one from build settings",
          );
          await writeFile(
            join(buildDir, "Dockerfile"),
            generateDockerfile(project.build),
          );
        }

        imageRef = `deplo/${slug}:${(commitSha || depId).slice(0, 12)}`;
        log(depId, "command", `docker build -t ${imageRef}`);
        await streamDocker(
          [
            "build",
            "-t",
            imageRef,
            "--label",
            "deplo.managed=true",
            "--label",
            `deplo.project=${project.id}`,
            "--label",
            `deplo.slug=${slug}`,
            buildDir,
          ],
          depId,
          900_000,
        );
      } finally {
        await rm(work, { recursive: true, force: true }).catch(() => {});
      }
    } else {
      throw new Error("Nothing to deploy: no Docker image or repository set");
    }

    const env = projectEnv(project.id);
    const composeYaml = renderCompose({
      name,
      image: imageRef,
      port: project.build.port,
      projectId: project.id,
      slug,
      domain,
      env,
    });
    await writeFile(stackFile, composeYaml);

    log(depId, "command", "docker compose up -d");
    await streamDocker(
      ["compose", "-p", name, "-f", stackFile, "up", "-d", "--remove-orphans"],
      depId,
      300_000,
    );

    log(depId, "info", "Waiting for the container to become healthy…");
    const running = await waitRunning(name, 60_000);
    const buildDurationMs = Date.now() - started;

    if (running) {
      setDep(depId, {
        status: "ready",
        readyAt: nowIso(),
        buildDurationMs,
        commitSha: commitSha || dep.commitSha,
      });
      setProject(project.id, { status: "active", productionUrl: dep.url });
      log(depId, "info", `Deployment ready at ${dep.url}`);
    } else {
      setDep(depId, { status: "error", buildDurationMs });
      setProject(project.id, { status: "error" });
      log(depId, "error", "Container did not reach a running state");
    }
  } catch (e) {
    log(depId, "error", e instanceof Error ? e.message : String(e));
    setDep(depId, { status: "error", buildDurationMs: Date.now() - started });
    setProject(project.id, { status: "error" });
  }
}

/** Stop a project's container. */
export async function stopContainer(slug: string): Promise<void> {
  await docker(["stop", `deplo-${slug}`], { timeout: 30_000 });
}

/** Start a previously stopped container. */
export async function startContainer(slug: string): Promise<void> {
  await docker(["start", `deplo-${slug}`], { timeout: 30_000 });
}

/** Stop and remove a project's stack. */
export async function destroyStack(slug: string): Promise<void> {
  const stackFile = join(STACK_DIR, `${slug}.yml`);
  try {
    await docker(["compose", "-p", `deplo-${slug}`, "-f", stackFile, "down"], {
      timeout: 60_000,
    });
  } catch {
    // Fall back to removing the container directly.
    await docker(["rm", "-f", `deplo-${slug}`], { timeout: 30_000 }).catch(
      () => {},
    );
  }
}
