import "server-only";

import { mkdtemp, mkdir, rm, writeFile, access } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { read, mutate } from "../store";
import { newId, nowIso } from "../ids";
import { decryptSecret } from "../crypto";
import { recordActivity } from "../data/activity";
import { docker, ensureNetwork } from "../infra/docker";
import { spawnStream } from "../infra/exec";
import { cloneStream, revParse } from "../infra/git";
import { generateDockerfile } from "./dockerfile";
import { previewDomain, instanceHost } from "./domains";
import { buildComposeStack } from "./compose-stack";
import { ensureAutoDomain } from "../data/domains";
import { installationCloneUrl } from "../github/app";
import type { Deployment, DeploymentEnvironment, LogLine, Server } from "../types";

const DATA_DIR = process.env.DEPLO_DATA_DIR || "/data";
const STACK_DIR = join(DATA_DIR, "stacks");

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function serverIp(server: Server | undefined): string {
  if (!server || server.type === "localhost") return instanceHost();
  return server.ip || instanceHost();
}

function log(depId: string, level: LogLine["level"], text: string): void {
  mutate((d) => {
    (d.logs[depId] ??= []).push({ ts: nowIso(), level, text });
  });
}

function setDep(depId: string, patch: Partial<Deployment>): void {
  mutate((d) => {
    const x = d.deployments.find((y) => y.id === depId);
    if (x) Object.assign(x, patch);
  });
}

function setProject(projectId: string, patch: Record<string, unknown>): void {
  mutate((d) => {
    const p = d.projects.find((x) => x.id === projectId);
    if (p) Object.assign(p, patch, { updatedAt: nowIso() });
  });
}

/** Decrypted env (project vars targeting production + attached shared groups). */
function projectEnv(projectId: string): Record<string, string> {
  const d = read();
  const out: Record<string, string> = {};
  for (const e of d.envVars) {
    if (e.projectId === projectId && e.targets.includes("production")) {
      out[e.key] = decryptSecret(e.valueEnc);
    }
  }
  for (const g of d.sharedEnvGroups ?? []) {
    if (g.projectIds.includes(projectId)) {
      for (const v of g.variables) out[v.key] = decryptSecret(v.valueEnc);
    }
  }
  return out;
}

function renderCompose(opts: {
  name: string;
  image: string;
  port: number;
  projectId: string;
  slug: string;
  domain: string;
  env: Record<string, string>;
}): string {
  const { name, image, port, projectId, slug, domain, env } = opts;
  // Traefik routing (TLS via Let's Encrypt). The global web->websecure redirect
  // is configured on the proxy, so no per-router middleware is needed here.
  const labels = [
    "traefik.enable=true",
    `traefik.http.routers.${name}.rule=Host(\`${domain}\`)`,
    `traefik.http.routers.${name}.entrypoints=websecure`,
    `traefik.http.routers.${name}.tls=true`,
    `traefik.http.routers.${name}.tls.certresolver=letsencrypt`,
    `traefik.http.services.${name}.loadbalancer.server.port=${port}`,
    "deplo.managed=true",
    `deplo.project=${projectId}`,
    `deplo.slug=${slug}`,
  ];
  const labelsYaml = labels.map((l) => `      - "${l}"`).join("\n");
  const envYaml = Object.keys(env).length
    ? "    environment:\n" +
      Object.entries(env)
        .map(([k, v]) => `      ${k}: ${JSON.stringify(v)}`)
        .join("\n") +
      "\n"
    : "";

  return `# Generated by Deplo  ${slug}
services:
  ${name}:
    image: ${image}
    container_name: ${name}
    restart: unless-stopped
    networks:
      - deplo
${envYaml}    labels:
${labelsYaml}

networks:
  deplo:
    external: true
`;
}

async function streamDocker(
  args: string[],
  depId: string,
  timeout: number,
): Promise<void> {
  const code = await spawnStream(
    "docker",
    args,
    (line) => log(depId, "info", line),
    { timeout },
  );
  if (code !== 0) throw new Error(`docker ${args[0]} failed (exit ${code})`);
}

async function waitRunning(name: string, ms: number): Promise<boolean> {
  const deadline = Date.now() + ms;
  while (Date.now() < deadline) {
    try {
      const { stdout } = await docker(
        ["inspect", "-f", "{{.State.Running}}", name],
        { timeout: 5_000 },
      );
      if (stdout.trim() === "true") return true;
    } catch {
      /* not up yet */
    }
    await sleep(2_000);
  }
  return false;
}

async function fileExists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * Create a deployment record (queued) and kick off the real build in the
 * background. Returns the deployment id immediately; the job updates status and
 * logs as it progresses.
 */
export function startDeployment(
  projectId: string,
  opts: {
    environment?: DeploymentEnvironment;
    creator: string;
    commitMessage?: string;
    branch?: string;
  },
): string {
  const project = read().projects.find((p) => p.id === projectId);
  if (!project) throw new Error("Project not found");
  const server = read().servers.find((s) => s.id === project.serverId);
  const ip = serverIp(server);
  const environment = opts.environment ?? "production";
  const branch = opts.branch ?? project.repo?.branch ?? "main";
  // Production routes through the project's registered primary domain (created
  // here if missing) so the generated hostname is the same one shown in the
  // Domains section and baked into a template's env. Previews are ephemeral.
  const domain =
    environment === "production"
      ? ensureAutoDomain(projectId, { slug: project.slug, ip })
      : previewDomain(project.slug, newId("").slice(1, 7), ip);
  const url = `https://${domain}`;
  const depId = newId("dpl");

  const dep: Deployment = {
    id: depId,
    projectId,
    status: "queued",
    environment,
    commitSha: "",
    commitMessage: opts.commitMessage ?? "Deploy",
    commitAuthor: opts.creator,
    branch,
    url,
    createdAt: nowIso(),
    readyAt: null,
    buildDurationMs: null,
    creator: opts.creator,
  };

  mutate((d) => {
    d.deployments.push(dep);
    d.logs[depId] = [];
    const p = d.projects.find((x) => x.id === projectId);
    if (p) {
      p.latestDeploymentId = depId;
      p.status = "queued";
      p.updatedAt = nowIso();
      if (environment === "production") p.productionUrl = url;
    }
  });
  recordActivity("deployment", `Deploying ${project.name}`, opts.creator, projectId);

  // Fire-and-forget: the standalone Node server keeps the event loop alive.
  void runDeployment(depId).catch((e) => {
    log(depId, "error", e instanceof Error ? e.message : String(e));
    setDep(depId, { status: "error" });
  });
  return depId;
}

async function runDeployment(depId: string): Promise<void> {
  const started = Date.now();
  const dep = read().deployments.find((x) => x.id === depId);
  if (!dep) return;
  const project = read().projects.find((p) => p.id === dep.projectId);
  if (!project) {
    setDep(depId, { status: "error" });
    return;
  }
  const slug = project.slug;
  const name = `deplo-${slug}`;
  const stackFile = join(STACK_DIR, `${slug}.yml`);
  const server = read().servers.find((s) => s.id === project.serverId);
  const ip = serverIp(server);
  const domain =
    dep.environment === "production"
      ? ensureAutoDomain(project.id, { slug, ip })
      : dep.url.replace(/^https?:\/\//, "");

  setDep(depId, { status: "building" });
  setProject(project.id, { status: "building" });

  try {
    await mkdir(STACK_DIR, { recursive: true });
    await ensureNetwork("deplo");

    // Multi-service compose / one-click template deploy: deploy the project's
    // own compose stack, wired to Traefik on the generated domain. The compose
    // interpolates its ${VARS} from an env-file we write alongside it. A real
    // repo/image source takes precedence over a stale compose (e.g. a template
    // edited and switched to GitHub).
    if (project.compose && project.compose.trim() && !project.repo && !project.dockerImage) {
      await deployComposeStack({
        depId,
        project,
        name,
        slug,
        stackFile,
        domain,
        environment: dep.environment,
        started,
      });
      return;
    }

    let imageRef: string;
    let commitSha = "";

    if (project.source === "docker-image" && project.dockerImage) {
      log(depId, "command", `docker pull ${project.dockerImage}`);
      await streamDocker(["pull", project.dockerImage], depId, 600_000);
      imageRef = project.dockerImage;
    } else if (project.repo) {
      const work = await mkdtemp(join(tmpdir(), "deplo-build-"));
      try {
        // Private GitHub repos clone through the connected App's short-lived
        // installation token; everything else uses the URL as-is. The token is
        // never logged.
        const cloneUrl = await installationCloneUrl(
          project.repo.url,
          project.repo.installationId ?? null,
        );
        log(depId, "command", `git clone ${project.repo.url} (${dep.branch})`);
        await cloneStream(cloneUrl, dep.branch, work, (line) =>
          log(depId, "info", line),
        );
        commitSha = await revParse(work);
        if (commitSha) setDep(depId, { commitSha });

        // Resolve the build dir, guarding against `..` escaping the clone.
        const rootRel = (project.build.rootDirectory || ".")
          .replace(/\\/g, "/")
          .replace(/^\.?\/?/, "");
        const candidate =
          rootRel && rootRel !== "." ? join(work, rootRel) : work;
        const buildDir = candidate.startsWith(work) ? candidate : work;

        if (!(await fileExists(join(buildDir, "Dockerfile")))) {
          log(
            depId,
            "info",
            "No Dockerfile found  generating one from build settings",
          );
          await writeFile(
            join(buildDir, "Dockerfile"),
            generateDockerfile(project.build),
          );
        }

        imageRef = `deplo/${slug}:${(commitSha || depId).slice(0, 12)}`;
        log(depId, "command", `docker build -t ${imageRef}`);
        await streamDocker(
          [
            "build",
            "-t",
            imageRef,
            "--label",
            "deplo.managed=true",
            "--label",
            `deplo.project=${project.id}`,
            "--label",
            `deplo.slug=${slug}`,
            buildDir,
          ],
          depId,
          900_000,
        );
      } finally {
        await rm(work, { recursive: true, force: true }).catch(() => {});
      }
    } else {
      throw new Error("Nothing to deploy: no Docker image or repository set");
    }

    const env = projectEnv(project.id);
    const composeYaml = renderCompose({
      name,
      image: imageRef,
      port: project.build.port,
      projectId: project.id,
      slug,
      domain,
      env,
    });
    await writeFile(stackFile, composeYaml);

    log(depId, "command", "docker compose up -d");
    await streamDocker(
      ["compose", "-p", name, "-f", stackFile, "up", "-d", "--remove-orphans"],
      depId,
      300_000,
    );

    log(depId, "info", "Waiting for the container to become healthy…");
    const running = await waitRunning(name, 60_000);
    const buildDurationMs = Date.now() - started;

    if (running) {
      setDep(depId, {
        status: "ready",
        readyAt: nowIso(),
        buildDurationMs,
        commitSha: commitSha || dep.commitSha,
      });
      setProject(project.id, {
        status: "active",
        ...(dep.environment === "production" ? { productionUrl: dep.url } : {}),
      });
      log(depId, "info", `Deployment ready at ${dep.url}`);
    } else {
      setDep(depId, { status: "error", buildDurationMs });
      setProject(project.id, { status: "error" });
      log(depId, "error", "Container did not reach a running state");
    }
  } catch (e) {
    log(depId, "error", e instanceof Error ? e.message : String(e));
    setDep(depId, { status: "error", buildDurationMs: Date.now() - started });
    setProject(project.id, { status: "error" });
  }
}

/**
 * Deploy a project's docker-compose stack (templates / multi-service apps).
 * Writes the stack and an env-file next to it, brings it up wired to Traefik on
 * the generated domain, and waits for the exposed service to come up.
 */
async function deployComposeStack(opts: {
  depId: string;
  project: {
    id: string;
    compose: string | null;
    expose: { service: string; port: number } | null;
    mounts?: { filePath: string; content: string }[] | null;
  };
  name: string;
  slug: string;
  stackFile: string;
  domain: string;
  environment: DeploymentEnvironment;
  started: number;
}): Promise<void> {
  const { depId, project, name, slug, stackFile, domain, environment, started } =
    opts;

  // Materialise any template config files into the project's isolated files dir
  // (referenced by the compose as ../files/<x>) BEFORE the stack comes up.
  const filesDir = join(STACK_DIR, "files", slug);
  if (project.mounts?.length) {
    await writeMountFiles(filesDir, project.mounts, depId);
  }

  const stackYaml = buildComposeStack({
    compose: project.compose ?? "",
    name,
    slug,
    projectId: project.id,
    domain,
    expose: project.expose ?? null,
    filesDir,
  });
  await writeFile(stackFile, stackYaml);

  // Env-file for ${VAR} interpolation. Written 0600 since it holds secrets.
  const env = projectEnv(project.id);
  const envFile = join(STACK_DIR, `${slug}.env`);
  await writeFile(envFile, renderEnvFile(env), { mode: 0o600 });

  log(depId, "command", "docker compose up -d");
  await streamDocker(
    [
      "compose",
      "-p",
      name,
      "-f",
      stackFile,
      "--env-file",
      envFile,
      "up",
      "-d",
      "--remove-orphans",
    ],
    depId,
    600_000,
  );

  log(depId, "info", "Waiting for the stack to become healthy…");
  const running = await waitStackRunning(slug, 90_000);
  const buildDurationMs = Date.now() - started;
  const url = `https://${domain}`;

  if (running) {
    setDep(depId, { status: "ready", readyAt: nowIso(), buildDurationMs });
    setProject(project.id, {
      status: "active",
      ...(environment === "production" ? { productionUrl: url } : {}),
    });
    log(depId, "info", `Deployment ready at ${url}`);
  } else {
    setDep(depId, { status: "error", buildDurationMs });
    setProject(project.id, { status: "error" });
    log(depId, "error", "Stack did not reach a running state");
  }
}

/**
 * Write template config files into the project's files dir, guarding against
 * path escape. Each filePath is treated as relative to filesDir; any `..`
 * segment or absolute path is rejected.
 */
async function writeMountFiles(
  filesDir: string,
  mounts: { filePath: string; content: string }[],
  depId: string,
): Promise<void> {
  for (const mount of mounts) {
    const rel = mount.filePath.replace(/^\.\/+/, "").replace(/^\/+/, "");
    if (rel.split(/[\\/]/).includes("..") || rel === "") {
      log(depId, "warn", `Skipping unsafe mount path: ${mount.filePath}`);
      continue;
    }
    const target = join(filesDir, rel);
    await mkdir(dirname(target), { recursive: true });
    // 0644: these are bind-mounted into the app container, which may run as a
    // non-root user and must be able to read its own config.
    await writeFile(target, mount.content, { mode: 0o644 });
  }
}

/** Serialize env to docker-compose env-file lines (KEY=VALUE, no quoting). */
function renderEnvFile(env: Record<string, string>): string {
  return (
    Object.entries(env)
      // env-file values are literal; strip newlines that would break the format.
      .map(([k, v]) => `${k}=${String(v).replace(/\r?\n/g, " ")}`)
      .join("\n") + "\n"
  );
}

/** Wait for a compose stack's exposed (Traefik-labelled) service to be running. */
async function waitStackRunning(slug: string, ms: number): Promise<boolean> {
  const deadline = Date.now() + ms;
  while (Date.now() < deadline) {
    try {
      const { stdout } = await docker(
        [
          "ps",
          "-q",
          "--filter",
          `label=deplo.slug=${slug}`,
          "--filter",
          "status=running",
        ],
        { timeout: 5_000 },
      );
      if (stdout.trim()) return true;
    } catch {
      /* not up yet */
    }
    await sleep(2_000);
  }
  return false;
}

function stackFilePath(slug: string): string {
  return join(STACK_DIR, `${slug}.yml`);
}

/** Stop a project's stack (compose-managed; falls back to the single container). */
export async function stopContainer(slug: string): Promise<void> {
  const stackFile = stackFilePath(slug);
  if (await fileExists(stackFile)) {
    await docker(["compose", "-p", `deplo-${slug}`, "-f", stackFile, "stop"], {
      timeout: 60_000,
    });
    return;
  }
  await docker(["stop", `deplo-${slug}`], { timeout: 30_000 });
}

/** Start a previously stopped stack. */
export async function startContainer(slug: string): Promise<void> {
  const stackFile = stackFilePath(slug);
  if (await fileExists(stackFile)) {
    await docker(["compose", "-p", `deplo-${slug}`, "-f", stackFile, "start"], {
      timeout: 60_000,
    });
    return;
  }
  await docker(["start", `deplo-${slug}`], { timeout: 30_000 });
}

/** Stop and remove a project's stack. */
export async function destroyStack(slug: string): Promise<void> {
  const stackFile = stackFilePath(slug);
  const envFile = join(STACK_DIR, `${slug}.env`);
  const args = ["compose", "-p", `deplo-${slug}`, "-f", stackFile];
  if (await fileExists(envFile)) args.push("--env-file", envFile);
  try {
    await docker([...args, "down", "--remove-orphans"], { timeout: 90_000 });
  } catch {
    // Fall back to removing a single labelled container directly.
    await docker(["rm", "-f", `deplo-${slug}`], { timeout: 30_000 }).catch(
      () => {},
    );
  }
  await rm(stackFile, { force: true }).catch(() => {});
  await rm(envFile, { force: true }).catch(() => {});
  await rm(join(STACK_DIR, "files", slug), {
    recursive: true,
    force: true,
  }).catch(() => {});
}
