/**
 * docker-compose generation for apps and databases.
 * Deplo turns a project's build config into a compose service wired to the
 * shared `deplo` Docker network and Traefik proxy.
 */
import type { BuildConfig, DatabaseType } from "../types";
import { traefikLabelsYaml } from "./traefik";
import { sslipDomain } from "./domains";

export interface AppComposeInput {
  name: string;
  image?: string;
  build: BuildConfig;
  domains: string[];
  env?: Record<string, string>;
}

export function generateAppCompose(input: AppComposeInput): string {
  const { name, build, domains, env = {} } = input;
  const envBlock = Object.keys(env).length
    ? "    environment:\n" +
      Object.entries(env)
        .map(([k, v]) => `      - ${k}=${v}`)
        .join("\n") +
      "\n"
    : "";
  const labels = traefikLabelsYaml({
    name,
    domains: domains.length ? domains : [sslipDomain(name)],
    port: build.port,
  });

  return `# Generated by Deplo  ${name}
services:
  ${name}:
    image: ${input.image ?? `deplo/${name}:latest`}
    restart: unless-stopped
    networks:
      - deplo
${envBlock}    labels:
${labels}

networks:
  deplo:
    external: true
`;
}

const DB_IMAGES: Record<DatabaseType, (v: string) => string> = {
  postgres: (v) => `postgres:${v}-alpine`,
  mysql: (v) => `mysql:${v}`,
  mariadb: (v) => `mariadb:${v}`,
  mongodb: (v) => `mongo:${v}`,
  redis: (v) => `redis:${v}-alpine`,
  clickhouse: (v) => `clickhouse/clickhouse-server:${v}`,
};

const DB_PORTS: Record<DatabaseType, number> = {
  postgres: 5432,
  mysql: 3306,
  mariadb: 3306,
  mongodb: 27017,
  redis: 6379,
  clickhouse: 8123,
};

export function generateDatabaseCompose(input: {
  name: string;
  type: DatabaseType;
  version: string;
  password: string;
  exposePort?: boolean;
}): string {
  const { name, type, version, password, exposePort } = input;
  const port = DB_PORTS[type];
  const image = DB_IMAGES[type](version);

  const envByType: Record<DatabaseType, string[]> = {
    postgres: [
      "POSTGRES_USER=app",
      `POSTGRES_PASSWORD=${password}`,
      `POSTGRES_DB=${name}`,
    ],
    mysql: [`MYSQL_ROOT_PASSWORD=${password}`, `MYSQL_DATABASE=${name}`],
    mariadb: [`MARIADB_ROOT_PASSWORD=${password}`, `MARIADB_DATABASE=${name}`],
    mongodb: [
      "MONGO_INITDB_ROOT_USERNAME=app",
      `MONGO_INITDB_ROOT_PASSWORD=${password}`,
    ],
    redis: [],
    clickhouse: ["CLICKHOUSE_USER=app", `CLICKHOUSE_PASSWORD=${password}`],
  };
  const command =
    type === "redis"
      ? `    command: redis-server --requirepass ${password}\n`
      : "";
  const envLines = envByType[type];
  const envBlock = envLines.length
    ? "    environment:\n" +
      envLines.map((l) => `      - ${l}`).join("\n") +
      "\n"
    : "";
  const ports = exposePort ? `    ports:\n      - "${port}:${port}"\n` : "";

  return `# Generated by Deplo  database ${name} (${type})
services:
  ${name}:
    image: ${image}
    restart: unless-stopped
    networks:
      - deplo
${command}${envBlock}${ports}    volumes:
      - ${name}-data:/var/lib/${type === "postgres" ? "postgresql/data" : type}
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ${name}-data:

networks:
  deplo:
    external: true
`;
}
