/**
 * docker-compose generation for databases.
 * Deplo turns a database request into a compose service wired to the shared
 * `deplo` Docker network. Databases are NOT publicly routed (no Traefik labels);
 * apps are rendered by the deploy engine (`build.ts` renderCompose), not here.
 */
import type { DatabaseType } from "../types";

const DB_IMAGES: Record<DatabaseType, (v: string) => string> = {
  postgres: (v) => `postgres:${v}-alpine`,
  mysql: (v) => `mysql:${v}`,
  mariadb: (v) => `mariadb:${v}`,
  mongodb: (v) => `mongo:${v}`,
  redis: (v) => `redis:${v}-alpine`,
  clickhouse: (v) => `clickhouse/clickhouse-server:${v}`,
};

const DB_PORTS: Record<DatabaseType, number> = {
  postgres: 5432,
  mysql: 3306,
  mariadb: 3306,
  mongodb: 27017,
  redis: 6379,
  clickhouse: 8123,
};

/**
 * The in-container path each engine's image actually writes its data to. The
 * named data volume MUST mount here or the data is not persisted (it lives in
 * the container's ephemeral layer and is lost on recreation) — and a backup
 * restore that writes to the engine's real data dir would land outside the
 * volume. These are the official images' documented data dirs:
 *  - postgres  /var/lib/postgresql/data
 *  - mysql     /var/lib/mysql
 *  - mariadb   /var/lib/mysql   (mariadb image reuses the mysql layout)
 *  - mongodb   /data/db
 *  - redis     /data
 *  - clickhouse /var/lib/clickhouse
 */
const DB_DATA_DIRS: Record<DatabaseType, string> = {
  postgres: "/var/lib/postgresql/data",
  mysql: "/var/lib/mysql",
  mariadb: "/var/lib/mysql",
  mongodb: "/data/db",
  redis: "/data",
  clickhouse: "/var/lib/clickhouse",
};

export function generateDatabaseCompose(input: {
  name: string;
  type: DatabaseType;
  version: string;
  password: string;
  /**
   * The HOST port to publish the engine on. When set, the compose maps
   * `hostPort:<engine-port>` so external clients reach the DB on the host's
   * `hostPort` (which the control plane validated is free on that host). Omitted
   * => the DB is NOT publicly published (internal `deplo`-network access only).
   */
  hostPort?: number;
}): string {
  const { name, type, version, password, hostPort } = input;
  const port = DB_PORTS[type];
  const image = DB_IMAGES[type](version);

  const envByType: Record<DatabaseType, string[]> = {
    postgres: [
      "POSTGRES_USER=app",
      `POSTGRES_PASSWORD=${password}`,
      `POSTGRES_DB=${name}`,
    ],
    mysql: [`MYSQL_ROOT_PASSWORD=${password}`, `MYSQL_DATABASE=${name}`],
    mariadb: [`MARIADB_ROOT_PASSWORD=${password}`, `MARIADB_DATABASE=${name}`],
    mongodb: [
      "MONGO_INITDB_ROOT_USERNAME=app",
      `MONGO_INITDB_ROOT_PASSWORD=${password}`,
    ],
    redis: [],
    // CLICKHOUSE_DB creates the logical database at provision time, like
    // POSTGRES_DB / MYSQL_DATABASE above. Without it the image only has the
    // built-in `default` DB, so the connection string's `db-<name>` database —
    // and every backup that dumps it — would target a database that never
    // exists (a silent empty backup + no-op restore).
    clickhouse: [
      "CLICKHOUSE_USER=app",
      `CLICKHOUSE_PASSWORD=${password}`,
      `CLICKHOUSE_DB=${name}`,
    ],
  };
  const command =
    type === "redis"
      ? `    command: redis-server --requirepass ${password}\n`
      : "";
  const envLines = envByType[type];
  const envBlock = envLines.length
    ? "    environment:\n" +
      envLines.map((l) => `      - ${l}`).join("\n") +
      "\n"
    : "";
  // Publish the engine port on the chosen HOST port when exposed. Bind to 0.0.0.0
  // explicitly so the mapping is reachable off-host regardless of the daemon's
  // default publish address (some hosts default published ports to 127.0.0.1,
  // which would make "expose publicly" only reachable from the host itself).
  const ports = hostPort
    ? `    ports:\n      - "0.0.0.0:${hostPort}:${port}"\n`
    : "";

  return `# Generated by Deplo  database ${name} (${type})
services:
  ${name}:
    image: ${image}
    container_name: ${name}
    restart: unless-stopped
    networks:
      - deplo
${command}${envBlock}${ports}    volumes:
      - ${name}-data:${DB_DATA_DIRS[type]}
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ${name}-data:

networks:
  deplo:
    external: true
`;
}
