import "server-only";

import { mkdir, writeFile, chmod } from "node:fs/promises";
import { join } from "node:path";
import { read } from "../store";
import { decryptSecret } from "../crypto";
import { docker, ensureNetwork } from "./docker";
import { dataVolumeHostMountpoint } from "../deploy/builders";
import type { DevSshUser } from "../types";

const DATA_DIR = process.env.DEPLO_DATA_DIR || "/data";
/** All gateway-managed files live here (host keys, sshd_config, wrapper, maps). */
const GW_DIR = join(DATA_DIR, "ssh-gateway");
const GW_STACK_FILE = join(GW_DIR, "docker-compose.yml");

/** Compose project + container names. */
export const GATEWAY_PROJECT = "deplo-ssh-gateway";
export const GATEWAY_CONTAINER = "deplo-ssh-gateway";
// The socket-filtering sidecar: a stock HAProxy with our default-deny allowlist
// (exec+inspect only). The only thing that mounts the raw docker socket.
const PROXY_CONTAINER = "deplo-ssh-gateway-proxy";
/** The ONE published SSH port (ADR-0002). */
export const GATEWAY_PORT = 2222;

/**
 * Bump when the gateway compose, sshd_config, or wrapper change so a running
 * gateway regenerates its config on the next ensureGateway() (sshd -t && HUP).
 */
const GATEWAY_VERSION = "6";

/** The Linux group every dev SSH user belongs to; the ForceCommand matches it. */
const DEV_GROUP = "devusers";
/**
 * The in-container exec target — ALWAYS this UID, never a name and never
 * client-supplied. UID 1000 is unambiguous and always exists after the dev
 * entrypoint (PLAN decision 5: "devuser = UID 1000, end-to-end"). Execing by
 * *name* would break on official images that ship a different UID-1000 user
 * (e.g. node:* ships `node`), and a username could be remapped to UID 0.
 */
const EXEC_UID = "1000";
/** The ForceCommand wrapper path inside the gateway. */
const WRAPPER_PATH = "/usr/local/bin/deplo-dev-shell";

// ---------------------------------------------------------------------------
// Managed config: the ForceCommand wrapper + sshd_config.
// ---------------------------------------------------------------------------

/**
 * The ForceCommand wrapper (root:root 0755). Reads $USER, sources its
 * root-owned map file (SLUG/DEV_CONTAINER only — never a target user), guards
 * that the target is a real dev container (and NOT the control-plane), checks
 * it is running, then `docker exec`s in as the HARDCODED literal `devuser`.
 * Ignores $SSH_ORIGINAL_COMMAND so `ssh host <cmd>` can't run arbitrary code.
 */
const WRAPPER_SCRIPT = `#!/bin/sh
# Generated by Deplo — un-bypassable ForceCommand for every dev SSH user.
set -eu

# sshd runs ForceCommand with a MINIMAL env — the gateway container's
# DOCKER_HOST is NOT inherited. Set it here so 'docker' talks to the socket
# proxy (the gateway has no raw socket); otherwise docker falls back to
# /var/run/docker.sock (absent here) and every call is "unreachable".
export DOCKER_HOST="tcp://proxy:2375"

MAP="/data/ssh-gateway/map/\${USER:-}"
if [ -z "\${USER:-}" ] || [ ! -f "$MAP" ]; then
  echo "deplo: no dev container is mapped to this account." >&2
  exit 1
fi

# The map file is root-OWNED (in a root-owned dir, so the user can't tamper with
# it) and world-readable; it sets only SLUG + DEV_CONTAINER (not secret). The
# exec user is NOT read from it — it is the hardcoded UID below.
SLUG=""
DEV_CONTAINER=""
. "$MAP"

# Guard: target must look like a dev container and must NOT be the control plane.
case "$DEV_CONTAINER" in
  deplo-dev-*) : ;;
  *)
    echo "deplo: refusing to exec into a non-dev container." >&2
    exit 1 ;;
esac
if [ "$DEV_CONTAINER" = "deplo" ] || [ "$DEV_CONTAINER" = "deplo-ssh-gateway" ]; then
  echo "deplo: refusing to exec into a control-plane container." >&2
  exit 1
fi

# Is the dev container running? (docker access is via the socket-proxy.) A
# freshly-Started container needs a few seconds to come up, and the proxy itself
# can be briefly unreachable right after a gateway/proxy restart. So we RETRY
# across a short grace window for every non-running state — including an empty
# result (proxy hiccup / container not yet created) — and only give up after the
# window. This avoids a spurious "stopped"/"missing" during a dashboard Start.
i=0
STATE=""
while [ "$i" -lt 15 ]; do
  # Empty when docker is unreachable OR the container doesn't exist (yet).
  STATE=$(docker inspect -f '{{.State.Status}}' "$DEV_CONTAINER" 2>/dev/null || true)
  case "$STATE" in
    running)
      break ;;
    exited|dead|paused)
      # Genuinely down — no point waiting.
      echo "deplo: your dev container is not running (status: $STATE)." >&2
      echo "deplo: Start it from the dashboard, then reconnect." >&2
      exit 1 ;;
    *)
      # restarting / created / "" (coming up, or proxy briefly unreachable) — wait.
      i=$((i + 1)); sleep 1; continue ;;
  esac
done
if [ "$STATE" != "running" ]; then
  echo "deplo: your dev container is not available yet (last status: \${STATE:-unreachable})." >&2
  echo "deplo: make sure dev mode is started in the dashboard, then reconnect." >&2
  exit 1
fi

# Dispatch on the client's request, ALWAYS execing into THIS user's dev
# container as the hardcoded UID ${EXEC_UID} (by UID, never a name, never the
# client). Running a client command is safe: the user already has a full shell
# in their own container as UID 1000, so an exec/sftp request grants no new
# privilege — the wrapper's job is to pin *which container* and *which user*,
# and that is unchanged across all three modes:
#   1. sftp subsystem      → run the container's sftp-server (SFTP, VS Code FS)
#   2. a client command    → run it in the container (scp, git, rsync, VS Code
#                            Remote-SSH bootstrap — its node server, etc.)
#   3. no command          → an interactive login shell
DEX="docker exec -i -u ${EXEC_UID} -w /workspace"
CMD="\${SSH_ORIGINAL_COMMAND:-}"

case "$CMD" in
  *sftp-server*|internal-sftp*|*"internal-sftp"*)
    # SFTP. Find the container's sftp-server (the dev entrypoint installs it);
    # path differs Debian vs Alpine. Run it (no TTY) as the dev user.
    exec docker exec -i -u ${EXEC_UID} -w /workspace "$DEV_CONTAINER" /bin/sh -lc '
      for s in /usr/lib/openssh/sftp-server /usr/libexec/sftp-server \\
               /usr/lib/ssh/sftp-server /usr/lib/sftp-server; do
        [ -x "$s" ] && exec "$s"
      done
      command -v sftp-server >/dev/null 2>&1 && exec sftp-server
      echo "deplo: sftp-server is not installed in this dev container." >&2
      exit 1' ;;
  "")
    # Interactive login shell (allocate a TTY). Prefer bash (the entrypoint
    # installs it) so the user gets a real bash prompt; fall back to sh.
    exec docker exec -it -u ${EXEC_UID} -w /workspace "$DEV_CONTAINER" \\
      /bin/sh -lc 'if command -v bash >/dev/null 2>&1; then exec bash -l; else exec \${SHELL:-/bin/sh} -l; fi' ;;
  *)
    # A specific command (scp/git/rsync/VS Code bootstrap). Run it verbatim in
    # the container's shell. No -t: piped/non-interactive, as the client expects.
    exec $DEX "$DEV_CONTAINER" /bin/sh -lc "$CMD" ;;
esac
`;

/**
 * sshd_config: a global Match for the dev group that forces the wrapper and
 * disables every forwarding/escape vector. Password auth is allowed at the
 * server level (some users opt in) but key auth is the default; brute-force
 * limits apply since the port is public.
 */
const SSHD_CONFIG = `# Generated by Deplo — SSH gateway (version ${GATEWAY_VERSION})
Port ${GATEWAY_PORT}
Protocol 2
HostKey /data/ssh-gateway/keys/ssh_host_ed25519_key
HostKey /data/ssh-gateway/keys/ssh_host_rsa_key

# Public port: limit brute-force exposure (password auth is an opt-in per user).
LoginGraceTime 20
MaxAuthTries 3
MaxStartups 10:30:60
PermitRootLogin no
UsePAM no

PasswordAuthentication yes
PubkeyAuthentication yes
AuthorizedKeysFile /data/ssh-gateway/keys/%u/authorized_keys

# A configured sftp subsystem so that an SFTP request runs the ForceCommand
# (with SSH_ORIGINAL_COMMAND set to it) instead of being rejected — the wrapper
# then routes it into the dev container's own sftp-server. 'internal-sftp' here
# is only the trigger token; no in-process sftp ever runs on the gateway.
Subsystem sftp internal-sftp

# Every dev user is forced through the wrapper and stripped of escape vectors.
# The wrapper still pins the container + UID for shell, exec, AND sftp requests.
# Forwarding is refused outright: the gateway sits on deplo-ssh-internal next to
# the docker socket-proxy (proxy:2375), so a forward to proxy:2375 would reach
# the docker API. ForceCommand does NOT restrict forwarding (it only governs the
# command/subsystem), so we deny it explicitly — AllowTcpForwarding no AND
# PermitOpen/PermitListen none (open-time denies that survive any later flip).
# Consequence: VS Code Remote-SSH cannot work here (it must forward to a server
# port that lives in the CONTAINER netns, unreachable from the gateway) — use
# VS Code Remote Tunnels / Dev Containers Attach instead.
Match Group ${DEV_GROUP}
  ForceCommand ${WRAPPER_PATH}
  PermitTTY yes
  AllowTcpForwarding no
  PermitOpen none
  PermitListen none
  AllowAgentForwarding no
  AllowStreamLocalForwarding no
  PermitTunnel no
  GatewayPorts no
  PermitUserRC no
  X11Forwarding no
`;

/**
 * The gateway container's own entrypoint (bind-mounted). Generates host keys
 * once, ensures the dev group exists, installs the wrapper + sshd_config from
 * the bind mount, reconciles accounts from a dumped state file, then runs sshd.
 * Accounts/keys are a disposable projection — /etc/passwd is never bind-mounted.
 */
const GATEWAY_ENTRYPOINT = `#!/bin/sh
set -eu
apk add --no-cache openssh docker-cli shadow >/dev/null 2>&1 || true

KEYS=/data/ssh-gateway/keys
mkdir -p "$KEYS"
[ -f "$KEYS/ssh_host_ed25519_key" ] || ssh-keygen -t ed25519 -f "$KEYS/ssh_host_ed25519_key" -N "" >/dev/null 2>&1
[ -f "$KEYS/ssh_host_rsa_key" ] || ssh-keygen -t rsa -b 4096 -f "$KEYS/ssh_host_rsa_key" -N "" >/dev/null 2>&1
chmod 600 "$KEYS"/ssh_host_* 2>/dev/null || true

getent group ${DEV_GROUP} >/dev/null 2>&1 || addgroup ${DEV_GROUP}

install -m 0755 /data/ssh-gateway/deplo-dev-shell ${WRAPPER_PATH}

mkdir -p /run/sshd /var/empty
exec /usr/sbin/sshd -D -f /data/ssh-gateway/sshd_config -e
`;

/**
 * Docker socket allowlist (ADR-0003, which-verb axis). A stock-image
 * `tecnativa/docker-socket-proxy` CANNOT separate `docker exec` from
 * `docker create`/`cp`/`start`: its `/containers` ACL is a single all-or-nothing
 * prefix, and `docker exec` itself needs `POST /containers/{id}/exec` (under
 * that prefix) + `POST=1`, which simultaneously opens `POST /containers/create`
 * and `PUT /containers/{id}/archive` (docker cp → host-fs write). So we ship our
 * OWN HAProxy config that DEFAULT-DENYs and allow-lists ONLY the exact endpoints
 * `docker exec`/`docker inspect` need. A total ForceCommand bypass then yields a
 * DOCKER_HOST that genuinely cannot create/start/cp/run — the real second layer.
 *
 * Allowed (and nothing else):
 *   GET  /_ping, /version                         (docker CLI handshake)
 *   GET  /containers/{id}/json                    (inspect → .State.Running)
 *   POST /containers/{id}/exec                    (create the exec instance)
 *   GET  /exec/{id}/json                          (exec inspect)
 *   POST /exec/{id}/start, /exec/{id}/resize      (run the exec)
 */
const SOCKET_FILTER_CFG = `# Generated by Deplo — docker socket allowlist (version ${GATEWAY_VERSION})
global
  log stdout format raw local0
  maxconn 256
  # Run as root so HAProxy can open the root-owned docker socket (mode 660). The
  # haproxy:*-alpine image otherwise drops to uid 99 and gets EACCES → 503.
  user root
  group root

defaults
  mode http
  log global
  option http-server-close
  timeout connect 10s
  timeout client 1h
  timeout server 1h
  timeout http-request 30s

frontend dockerfilter
  bind *:2375
  # ---- ALLOW-LIST (anything not matched hits the default deny below) ----
  # docker CLI handshake.
  http-request allow if { method GET } { path,url_dec -m reg -i ^(/v[0-9.]+)?/_ping$ }
  http-request allow if { method GET } { path,url_dec -m reg -i ^(/v[0-9.]+)?/version$ }
  # Inspect an existing container (the wrapper's running-check).
  http-request allow if { method GET } { path,url_dec -m reg -i ^(/v[0-9.]+)?/containers/[a-zA-Z0-9_.-]+/json$ }
  # Create + run an exec instance INSIDE an existing container.
  http-request allow if { method POST } { path,url_dec -m reg -i ^(/v[0-9.]+)?/containers/[a-zA-Z0-9_.-]+/exec$ }
  http-request allow if { method GET }  { path,url_dec -m reg -i ^(/v[0-9.]+)?/exec/[a-zA-Z0-9_.-]+/json$ }
  http-request allow if { method POST } { path,url_dec -m reg -i ^(/v[0-9.]+)?/exec/[a-zA-Z0-9_.-]+/start$ }
  http-request allow if { method POST } { path,url_dec -m reg -i ^(/v[0-9.]+)?/exec/[a-zA-Z0-9_.-]+/resize$ }
  # ---- DEFAULT DENY: create, start, cp/archive, kill, run, images, attach … ----
  http-request deny deny_status 403
  default_backend dockersock

backend dockersock
  # The 'unix@' prefix is REQUIRED for a unix-socket server — a bare path is
  # parsed as a TCP address and yields 503 "no server available".
  server dockerd unix@/var/run/docker.sock
`;

// ---------------------------------------------------------------------------
// Gateway compose (2 services — socket filter + gateway). ADR-0003.
// ---------------------------------------------------------------------------

/** Render the gateway's docker-compose (host-translated bind paths). */
function renderGatewayCompose(gwHostDir: string): string {
  return `# Generated by Deplo — SSH gateway (version ${GATEWAY_VERSION})
services:
  proxy:
    image: haproxy:2.9-alpine
    container_name: ${PROXY_CONTAINER}
    restart: unless-stopped
    # Start as root so HAProxy's master can open the root-owned docker socket
    # (mode 660); the image otherwise runs as uid 99 and gets EACCES → 503. The
    # 'user root' directive in the config keeps the workers as root too.
    user: "0:0"
    # The ONLY thing that mounts the raw socket; fronts it with a default-deny
    # allowlist (exec+inspect only — no create/start/cp/run). See SOCKET_FILTER_CFG.
    command: ["haproxy", "-f", "/data/ssh-gateway/socket-filter.cfg"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${JSON.stringify(`${gwHostDir}:/data/ssh-gateway:ro`)}
    networks:
      - deplo-ssh-internal
    labels:
      - "deplo.managed=true"
      - "deplo.role=ssh-gateway-proxy"

  gateway:
    image: alpine:3.20
    container_name: ${GATEWAY_CONTAINER}
    restart: unless-stopped
    depends_on:
      - proxy
    # Talks docker ONLY through the proxy — never sees the raw socket.
    environment:
      DOCKER_HOST: "tcp://proxy:2375"
    entrypoint: ["/bin/sh", "/data/ssh-gateway/gateway-entrypoint"]
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    volumes:
      - ${JSON.stringify(`${gwHostDir}:/data/ssh-gateway`)}
    networks:
      - deplo-ssh-internal
    labels:
      - "deplo.managed=true"
      - "deplo.role=ssh-gateway"

networks:
  deplo-ssh-internal:
    driver: bridge
`;
}

/** Write all gateway-managed config files (idempotent). */
async function writeGatewayFiles(): Promise<void> {
  await mkdir(join(GW_DIR, "keys"), { recursive: true });
  await mkdir(join(GW_DIR, "map"), { recursive: true });

  const mountpoint = await dataVolumeHostMountpoint();
  const gwHostDir =
    mountpoint && GW_DIR.startsWith(DATA_DIR)
      ? join(mountpoint, GW_DIR.slice(DATA_DIR.length))
      : GW_DIR;

  await writeFile(GW_STACK_FILE, renderGatewayCompose(gwHostDir));
  await writeFile(join(GW_DIR, "socket-filter.cfg"), SOCKET_FILTER_CFG);
  await writeFile(join(GW_DIR, "sshd_config"), SSHD_CONFIG);
  await writeFile(join(GW_DIR, "deplo-dev-shell"), WRAPPER_SCRIPT, { mode: 0o755 });
  await chmod(join(GW_DIR, "deplo-dev-shell"), 0o755).catch(() => {});
  await writeFile(join(GW_DIR, "gateway-entrypoint"), GATEWAY_ENTRYPOINT, {
    mode: 0o755,
  });
  await chmod(join(GW_DIR, "gateway-entrypoint"), 0o755).catch(() => {});
}

/** Is the gateway container currently running? */
async function gatewayRunning(): Promise<boolean> {
  try {
    const { stdout } = await docker(
      ["inspect", "-f", "{{.State.Running}}", GATEWAY_CONTAINER],
      { timeout: 10_000, noThrow: true },
    );
    return stdout.trim() === "true";
  } catch {
    return false;
  }
}

/**
 * Lazily create the gateway on the first SSH user (ADR-0002) — never at install.
 * Idempotent, like ensureNetwork: writes config, brings the 2-service stack up,
 * then reconciles every stored DevSshUser into the fresh container. Safe to call
 * on every startDev / addDevSshUser.
 */
export async function ensureGateway(): Promise<void> {
  await ensureNetwork("deplo");
  await writeGatewayFiles();
  await docker(
    ["compose", "-p", GATEWAY_PROJECT, "-f", GW_STACK_FILE, "up", "-d", "--remove-orphans"],
    { timeout: 180_000 },
  );
  await waitGatewayReady(60_000);
  await reconcileGateway();
}

/** Poll until sshd is up inside the gateway (the entrypoint installs it). */
async function waitGatewayReady(timeoutMs: number): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const { stdout } = await docker(
        ["exec", GATEWAY_CONTAINER, "sh", "-c", "command -v sshd >/dev/null && echo ok"],
        { timeout: 10_000, noThrow: true },
      );
      if (stdout.trim() === "ok") return;
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 1500));
  }
}

// ---------------------------------------------------------------------------
// Per-user provisioning — store leads, gateway exec follows. No sshd reload.
// ---------------------------------------------------------------------------

/** Look up the dev container name for a user's project (for the map file). */
function devContainerForProject(projectId: string): {
  slug: string;
  container: string;
} | null {
  const p = read().projects.find((x) => x.id === projectId);
  if (!p) return null;
  return { slug: p.slug, container: `deplo-dev-${p.slug}` };
}

/** Run a command inside the gateway container. */
function gwExec(args: string[], opts: { input?: string } = {}) {
  return docker(["exec", "-i", GATEWAY_CONTAINER, ...args], {
    timeout: 30_000,
    input: opts.input,
    noThrow: true,
  });
}

/**
 * Provision one user inside the running gateway (no sshd reload — sshd reads
 * accounts/keys/maps per-connection). Creates the locked-down account, sets the
 * credential(s), writes authorized_keys (key users) and the root-owned map file.
 * Decrypts the password just-in-time; it is never passed via env or argv that
 * `docker inspect` could surface.
 */
export async function provisionUser(user: DevSshUser): Promise<void> {
  const target = devContainerForProject(user.projectId);
  if (!target) return;

  // 1. Account: shell is the wrapper; member of the dev group. Idempotent.
  await gwExec([
    "sh",
    "-c",
    `id ${shellQuote(user.username)} >/dev/null 2>&1 || ` +
      `adduser -D -G ${DEV_GROUP} -s ${WRAPPER_PATH} ${shellQuote(user.username)}`,
  ]);

  // 2. Credentials. For a key-only user, DISABLE password login (shadow = "*")
  // but do NOT *lock* the account: with `UsePAM no`, a locked account ("!...")
  // is refused for EVERY auth method — including the public key the user relies
  // on ("account is locked"). "*" forbids password auth while leaving pubkey
  // auth working, which is exactly what a key-only user needs.
  if (user.passwordEnc) {
    const pw = decryptSecret(user.passwordEnc);
    // Pass cleartext over STDIN, never argv/env (inspect-safe). chpasswd reads
    // "user:password" from stdin.
    await gwExec(["sh", "-c", "chpasswd"], {
      input: `${user.username}:${pw}\n`,
    });
  } else {
    // usermod -p '*' sets the shadow hash to a value no password can match,
    // without setting the lock flag. (passwd -l would prepend '!' → locked.)
    await gwExec(["usermod", "-p", "*", user.username]);
  }

  // 3. authorized_keys (key users only). sshd reads this AS the connecting user
  // (after dropping privileges), so a root:root 0600 file is unreadable by them
  // ("Could not open authorized keys: Permission denied"). It must be
  // world-READABLE; StrictModes still passes because it is root-OWNED and not
  // group/other-WRITABLE (0644). The key itself is public, so 0644 leaks
  // nothing. `restrict` keeps the session locked down regardless.
  const keyDir = `/data/ssh-gateway/keys/${user.username}`;
  if (user.publicKey && user.publicKey.trim()) {
    const line = `restrict,pty ${user.publicKey.trim()}\n`;
    await gwExec(["sh", "-c", `mkdir -p ${shellQuote(keyDir)} && chmod 755 ${shellQuote(keyDir)}`]);
    await gwExec(
      ["sh", "-c", `cat > ${shellQuote(`${keyDir}/authorized_keys`)} && chmod 644 ${shellQuote(`${keyDir}/authorized_keys`)}`],
      { input: line },
    );
  } else {
    await gwExec(["sh", "-c", `rm -rf ${shellQuote(keyDir)}`]);
  }

  // 4. Map file (atomic tmp+rename). SLUG + DEV_CONTAINER only — NOT secret (the
  // container name is derivable from the slug). It must be world-READABLE (0644)
  // because the ForceCommand wrapper sources it while running AS the SSH user,
  // not root — sshd drops to the user's UID before ForceCommand. It stays
  // root-OWNED in a root-owned dir so the user can read but not tamper with
  // their own exec target.
  const mapBody =
    `SLUG=${shellQuote(target.slug)}\n` +
    `DEV_CONTAINER=${shellQuote(target.container)}\n`;
  const mapPath = `/data/ssh-gateway/map/${user.username}`;
  await gwExec(
    [
      "sh",
      "-c",
      `umask 022 && cat > ${shellQuote(`${mapPath}.tmp`)} && ` +
        `chown root:root ${shellQuote(`${mapPath}.tmp`)} && ` +
        `chmod 644 ${shellQuote(`${mapPath}.tmp`)} && ` +
        `mv ${shellQuote(`${mapPath}.tmp`)} ${shellQuote(mapPath)}`,
    ],
    { input: mapBody },
  );
}

/** Remove one user from the gateway (account + key + map files). */
export async function deprovisionUser(username: string): Promise<void> {
  if (!(await gatewayRunning())) return;
  // Hard-evict any live session first, then drop the account + files.
  await gwExec(["sh", "-c", `pkill -u ${shellQuote(username)} 2>/dev/null || true`]);
  await gwExec([
    "sh",
    "-c",
    `deluser ${shellQuote(username)} 2>/dev/null || true`,
  ]);
  await gwExec([
    "sh",
    "-c",
    `rm -rf /data/ssh-gateway/keys/${shellQuote(username)} ` +
      `/data/ssh-gateway/map/${shellQuote(username)}`,
  ]);
}

/**
 * Rebuild the gateway's account/key/map projection from the store (the sole
 * source of truth — ADR-0002). Called on gateway first boot and after drift.
 * The store always leads; a reconcile after any mutation is always correct.
 */
export async function reconcileGateway(): Promise<void> {
  if (!(await gatewayRunning())) return;
  const users = read().devSshUsers;
  for (const u of users) {
    await provisionUser(u).catch(() => {});
  }
}

/** Quote a value for safe interpolation into a `sh -c` string. */
function shellQuote(s: string): string {
  return `'${String(s).replace(/'/g, `'\\''`)}'`;
}
