import "server-only";

// https://deplo.build/docs/guides/data/databases

import { and, eq } from "drizzle-orm";

import { assertServerAccessibleTx } from "../servers/team-access";
import { getDb } from "../../db/client";
import { databases as databasesTable } from "../../db/schema/control-plane/databases";
import { pendingTeardowns as pendingTeardownsTable } from "../../db/schema/control-plane/deployments";
import { databaseToRow } from "../backup-rows";
import { getCurrentUser } from "../../auth/current-user";
import { newId, nowIso } from "../../ids";
import { requireCapability, canExposePorts } from "../../membership";
import { recordActivity } from "../activity";
import { dispatchAlert } from "../../notify/dispatch";
import { encryptSecret, randomToken } from "../../crypto";
import { connectAgent } from "../../infra/agent-client/connect";
import { buildConnectionString } from "../../deploy/database-compose";
import { assertNoNameClash, withNetworkLock } from "../name-clash";
import { environmentInTeam } from "../environments";
import {
  MIN_USER_PORT,
  MAX_PORT,
  isValidExposePort,
} from "../../databases/ports";
import { withKeyedLock } from "../keyed-mutex";
import { assertPasswordNotPwned } from "../../pwned-password";
import { assertPasswordPolicy } from "../../password-policy";
import { publishDatabaseChanged } from "../../graphql/pubsub";
import {
  DEFAULT_PORTS,
  assertPasswordSafe,
  cleanDatabaseName,
  databaseSlug,
  defaultUserFor,
  isValidImageRef,
  sanitizeDbIdentifier,
} from "./validate";
import { databaseExists, toDTO, type DatabaseDTO } from "./rows";
import { renderDatabaseStackYaml, rerouteRequest } from "./stack";
import { assertHostPortAvailable, resolveTeamServer } from "./server-ports";
import type { Database, DatabaseType } from "../../types/database";

export async function createDatabase(input: {
  name: string;
  type: DatabaseType;
  version: string;
  serverId?: string;
  environmentId?: string | null;
  username?: string;
  /**
   * The logical database to create. Falls back to the service name, which is
   * what databases created before this input used, so backups keep dumping the
   * identical database.
   */
  dbName?: string;
  password?: string;
  /** The supplied password was GENERATED by a machine, not typed by a person -
   *  today that is an import carrying another platform's credential. */
  passwordIsGenerated?: boolean;
  exposedPublicly?: boolean;
  exposedPort?: number;
  customImage?: string | null;
}): Promise<DatabaseDTO> {
  const { membership } = await requireCapability("create_databases");
  const teamId = membership.teamId;
  const user = (await getCurrentUser())!;
  const name = cleanDatabaseName(input.name);
  const slug = databaseSlug(name);
  // The version is interpolated raw into the compose `image:` scalar, so it is
  // validated as an image tag up front.
  if (!/^[A-Za-z0-9._-]+$/.test(input.version))
    throw new Error("Version must be a valid image tag.");
  const customImage = input.customImage?.trim() || null;
  if (customImage && !isValidImageRef(customImage))
    throw new Error(
      "Custom image must be a plain image reference (repo[:tag] or repo@digest) with no spaces or quotes.",
    );
  // Cheap local input validation, so fail fast (before any server lookup or
  // agent probe) rather than only after the slower checks.
  if (input.password) {
    assertPasswordSafe(input.password);
    if (!input.passwordIsGenerated) {
      assertPasswordPolicy(input.password);
      await assertPasswordNotPwned(input.password);
    }
  }

  const exposed = input.exposedPublicly ?? false;
  // Publishing a host port is privileged: the same canExposePorts grant that
  // gates a project's compose `ports:`. Fail BEFORE any work.
  if (exposed && !(await canExposePorts()))
    throw new Error("You don't have permission to publish ports");

  const server = await resolveTeamServer(teamId, input.serverId);

  // The display name is unique per team (`databases_team_name_uq`). Check it
  // here so a duplicate reads as a sentence, like renameDatabase.
  const nameTaken = await getDb()
    .select({ id: databasesTable.id })
    .from(databasesTable)
    .where(
      and(eq(databasesTable.teamId, teamId), eq(databasesTable.name, name)),
    )
    .limit(1);
  if (nameTaken.length > 0)
    throw new Error(`A database named "${name}" already exists in this team.`);

  // The stack slug, its container_name and its data volume are a GLOBAL
  // namespace on the host, but the DB name is only unique per-team, and servers
  // are shared cross-team.
  const slugCollision = await getDb()
    .select({ id: databasesTable.id })
    .from(databasesTable)
    .where(
      and(
        eq(databasesTable.serverId, server.id),
        eq(databasesTable.host, `db-${slug}`),
      ),
    )
    .limit(1);
  if (slugCollision.length > 0)
    throw new Error(
      `A database stack named "db-${slug}" already exists on ${server.name}. Database stacks share a per-host namespace - pick a different name.`,
    );
  // A deleted database whose teardown the host has not confirmed yet still owns
  // that name and its data volume there; a new stack would adopt them.
  const pending = await getDb()
    .select({ id: pendingTeardownsTable.id })
    .from(pendingTeardownsTable)
    .where(
      and(
        eq(pendingTeardownsTable.serverId, server.id),
        eq(pendingTeardownsTable.deployKey, `db-${slug}`),
      ),
    )
    .limit(1);
  if (pending.length > 0)
    throw new Error(
      `A database stack named "db-${slug}" is still being removed from ${server.name}. Pick a different name, or wait for that removal to finish.`,
    );

  let exposedPort: number | null = null;
  if (exposed) {
    if (input.exposedPort == null)
      throw new Error(
        "A host port is required to expose the database publicly",
      );
    if (!isValidExposePort(input.exposedPort))
      throw new Error(
        `Port ${input.exposedPort} is invalid - choose an unprivileged port (${MIN_USER_PORT}-${MAX_PORT})`,
      );
    await assertHostPortAvailable(server, input.exposedPort);
    exposedPort = input.exposedPort;
  }

  const port = DEFAULT_PORTS[input.type];
  // Connection strings reference it, so it must stay stable - it is stored in
  // `host` and never re-derived (a rename leaves it alone).
  const service = `db-${slug}`;

  const username =
    input.type === "redis"
      ? "default"
      : ((input.username ? sanitizeDbIdentifier(input.username) : null) ??
        defaultUserFor(input.type));
  const dbName =
    (input.dbName ? sanitizeDbIdentifier(input.dbName) : null) ?? service;
  const password =
    input.password && input.password.length > 0
      ? input.password
      : randomToken(12);

  // The placement, resolved before any write - a foreign Environment is refused
  // here, not silently dropped.
  const environmentId = input.environmentId
    ? ((await environmentInTeam(input.environmentId, teamId))?.id ??
      (() => {
        throw new Error("Environment not found");
      })())
    : null;

  const conn = buildConnectionString({
    type: input.type,
    username,
    password,
    host: exposedPort != null ? server.host : service,
    port: exposedPort != null ? exposedPort : port,
    dbName,
  });

  const db: Database = {
    id: newId("db"),
    teamId,
    environmentId,
    name,
    // Provisioned here, from nothing. Only a migration can hand a database a
    // volume that was supposed to arrive from another host and did not.
    dataCopyError: "",
    migrationRunId: null,
    // No logo of its own: the UI shows the engine's real brand mark.
    logo: null,
    type: input.type,
    version: input.version,
    username,
    dbName,
    status: "provisioning",
    serverId: server.id,
    host: service,
    port,
    connectionStringEnc: encryptSecret(conn),
    exposedPublicly: exposed,
    exposedPort,
    resources: null,
    customImage,
    customCommand: null,
    cronEnabled: false,
    mounts: [],
    sizeMb: 0,
    createdAt: nowIso(),
  };
  // Under the same lock the moves take: the check and the insert are two
  // statements, and two concurrent creates otherwise both read the name as free.
  await withNetworkLock({ teamId, environmentId }, async () => {
    await assertNoNameClash({
      to: { teamId, environmentId, serverId: server.id },
      claims: [service],
      exceptId: "",
      subject: "the database",
    });
    // Re-assert server access inside a tx (SHARE-locks the server row) so a
    // concurrent setServerTeams restrict can't land this database on a server
    // the team just lost access to - pairs with setServerTeams' FOR UPDATE lock.
    await getDb().transaction(async (tx) => {
      await assertServerAccessibleTx(tx, server.id, teamId);
      await tx.insert(databasesTable).values(databaseToRow(db));
    });
  });
  await recordActivity(
    "database",
    `Created database ${name} (${input.type})`,
    user.name,
    null,
    teamId,
    null,
    db.id,
  );

  void provisionDatabase(db, password).catch(async (e: unknown) => {
    const why = e instanceof Error ? e.message : String(e);
    console.error(
      `[deplo] database ${name} (${db.id}) failed to provision: ${why}`,
    );
    // Only if the row still exists (a concurrent delete may have raced the
    // floated provision; an UPDATE matching no row is a safe no-op).
    await getDb()
      .update(databasesTable)
      .set({ status: "error" })
      .where(eq(databasesTable.id, db.id));
    publishDatabaseChanged(db.id);
    // The request that asked for this database is long gone - this catch is
    // floated, so the alert is the only way anybody learns it never came up.
    dispatchAlert({
      teamId,
      key: "database_failed",
      title: `Database ${name} could not be set up`,
      body: `It was created but never finished provisioning on its server: ${why}`,
      path: "/storage",
    });
  });

  return toDTO(db);
}

// provisionDatabase - bring the DB stack up on the owning server's agent.
async function provisionDatabase(
  db: Database,
  password: string,
): Promise<void> {
  const yaml = renderDatabaseStackYaml(db, password);
  // Under the DB's lifecycle lock so a concurrent delete can't interleave: a
  // delete issued during provisioning WAITS here, then tears down a
  // fully-created stack (no orphan).
  await withKeyedLock(db.id, async () => {
    if (!(await databaseExists(db.id))) return; // deleted before us
    const conn = await connectAgent(db.serverId);
    try {
      const res = await conn.reroute(rerouteRequest(db, yaml));
      if (!res.ok)
        throw new Error(res.error || "agent failed to provision the database");
    } finally {
      conn.close();
    }
    await getDb()
      .update(databasesTable)
      .set({ status: "running" })
      .where(eq(databasesTable.id, db.id));
    publishDatabaseChanged(db.id);
    dispatchAlert({
      teamId: db.teamId,
      key: "database_ready",
      title: `Database ${db.name} is ready`,
      body: "It finished setting up and is accepting connections.",
      path: "/storage",
    });
  });
}
