/**
 * The two words baked into every generated hostname. Curated rather than taken
 * from a general-purpose dictionary: that one produced `whoami-obnoxious-kite`
 * and `stack-demo-fat-hookworm`, and the URL Deplo hands you on your first
 * deploy is the first thing you show somebody.
 *
 * Uniqueness does not rest here - the app's own label and the hex IP are already
 * in the name - so a short, safe list is enough.
 */

export const FRIENDLY_ADJECTIVES: readonly string[] = [
  "amber",
  "ancient",
  "autumn",
  "azure",
  "bold",
  "brave",
  "breezy",
  "bright",
  "brisk",
  "calm",
  "cheerful",
  "clever",
  "cosmic",
  "crimson",
  "crystal",
  "dawn",
  "eager",
  "electric",
  "emerald",
  "gentle",
  "gilded",
  "golden",
  "graceful",
  "happy",
  "hidden",
  "humble",
  "indigo",
  "ivory",
  "jolly",
  "keen",
  "lively",
  "lucky",
  "lunar",
  "merry",
  "mighty",
  "misty",
  "noble",
  "polar",
  "prime",
  "quiet",
  "rapid",
  "royal",
  "rustic",
  "sapphire",
  "scarlet",
  "serene",
  "silver",
  "smooth",
  "solar",
  "spry",
  "steady",
  "sunny",
  "swift",
  "tidy",
  "tranquil",
  "velvet",
  "vivid",
  "warm",
  "wise",
  "witty",
];

export const FRIENDLY_ANIMALS: readonly string[] = [
  "albatross",
  "antelope",
  "badger",
  "beaver",
  "bison",
  "cheetah",
  "condor",
  "coral",
  "cricket",
  "dolphin",
  "dragonfly",
  "eagle",
  "egret",
  "falcon",
  "ferret",
  "finch",
  "flamingo",
  "gazelle",
  "gecko",
  "heron",
  "ibex",
  "impala",
  "jaguar",
  "kestrel",
  "kingfisher",
  "koala",
  "lemur",
  "leopard",
  "lynx",
  "macaw",
  "manatee",
  "marmot",
  "meerkat",
  "narwhal",
  "ocelot",
  "orca",
  "osprey",
  "otter",
  "panda",
  "pelican",
  "penguin",
  "puffin",
  "quokka",
  "raven",
  "robin",
  "seal",
  "sparrow",
  "starling",
  "swallow",
  "swan",
  "tapir",
  "toucan",
  "turtle",
  "walrus",
  "wombat",
  "wren",
];

/** One `adjective-animal` pair, e.g. `swift-otter`. */
export function friendlyWords(): string {
  const pick = (list: readonly string[]) =>
    list[Math.floor(Math.random() * list.length)]!;
  return `${pick(FRIENDLY_ADJECTIVES)}-${pick(FRIENDLY_ANIMALS)}`;
}
