-- An app remembers which JavaScript framework Deplo recognised in its source.
--
-- Vercel-style recognition: on every deploy that runs one of the auto-detecting
-- builders (Nixpacks / Railpack), Deplo reads the app's own package.json + root
-- config files and names what it found - "nextjs", "astro", "nestjs", … (the ids
-- in lib/apps/framework-catalog.ts). The UI shows that name with the project's
-- real brand mark, and the app's container port defaults to the port that
-- framework's production server actually binds instead of a hardcoded 3000.
--
-- The column is DERIVED, not a setting. There is no mutation that writes it and
-- no "framework preset" the user picks: each deploy re-detects and overwrites, so
-- a repo that switches frameworks corrects itself on its next deploy, and an app
-- whose build method moves off Nixpacks/Railpack goes back to NULL. That is also
-- why nothing is backfilled - every existing row is NULL until its next deploy,
-- which is the correct value in the meantime.
--
-- Plain text with no CHECK constraint, matching how `apps.build_method` is
-- stored: an id written by a newer catalog than the binary reading it must
-- round-trip untouched (the UI falls back to no badge for an id it doesn't know)
-- rather than fail the row.
ALTER TABLE "apps" ADD COLUMN "framework" text;
