-- An app can add its own flags to the `docker compose up` that brings it up.
--
-- Deplo assembles that command itself - `compose -p deplo-<slug> -f <stack>.yml
-- [--env-file …] up -d --remove-orphans`, and there was no way to influence it.
-- Real deploys occasionally need one more flag on it: `--pull always` for a
-- floating image tag, `--scale web=3`, `--renew-anon-volumes`.
--
-- Stored as the RAW string the operator typed; the deploy edge splits it on
-- whitespace into argv tokens (lib/deploy/compose-args.ts) and the agent appends
-- them to the command it assembles. NULL/empty for every existing app, which is
-- exactly the untouched command they run today.
--
-- Deliberately additive flags, NOT the "custom command" other platforms ship
-- (where the operator retypes the whole invocation from what the UI prints). That
-- design rots the day the platform's own command changes, and one typo in the
-- project name or stack path aims compose at nothing - a green deploy of an app
-- that never restarted. Both sides here refuse the flags that decide WHICH stack
-- comes up (-p/--project-name, -f/--file, --env-file, --project-directory): the
-- control plane won't store them, and the agent drops the whole set if one
-- arrives anyway.
--
-- Needs deplo-agent capability "deploy.compose-args"; an older agent ignores the
-- field, so the deploy log says so rather than letting the flags vanish silently.
ALTER TABLE "apps" ADD COLUMN IF NOT EXISTS "compose_up_args" text;
