/**
 * End-to-end smoke test for MULTI-SERVICE COMPOSE STACK deploys via the agent
 * (the remote-server compose path). Drives the REAL agent over mTLS against real
 * Docker with a SOURCE_KIND_COMPOSE deploy, then asserts what the control plane
 * relies on: every service comes up labelled with deplo.slug, the agent wrote the
 * --env-file (so `${VAR}` interpolation works), and a template mount file landed
 * under the project files dir and is bind-mounted into the container.
 *
 * The "remote" path is simulated by the LOCAL agent over loopback mTLS (the
 * sandbox has no second host); the wire contract is identical to a real remote.
 * Run with: npx tsx scripts/agent-compose-e2e.mts
 *
 * Not part of `npm test` (needs Docker + the built binary).
 */
import { spawn } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

process.env.DEPLO_SECRET ||= "e2e-agent-secret-aaaaaaaaaaaaaaaaaaaa";
const DATA = mkdtempSync(join(tmpdir(), "deplo-agent-compose-e2e-"));
process.env.DEPLO_DATA_DIR = DATA;
process.env.DEPLO_AGENT_BIN = join(process.cwd(), "agent/bin/deplo-agent");
process.env.DEPLO_AGENT_ADDR = "127.0.0.1:19445"; // avoid clashing with other e2e
process.env.DEPLO_AGENT_STACK_DIR = join(DATA, "stacks");

const SLUG = "agent-compose-e2e";
const PROJECT_ID = "prj_compose_e2e";
const COMPOSE_PROJECT = `deplo-${SLUG}`;

function sh(cmd: string, args: string[]): Promise<{ code: number; out: string }> {
  return new Promise((resolve) => {
    const c = spawn(cmd, args, { windowsHide: true });
    let out = "";
    c.stdout.on("data", (d) => (out += d));
    c.stderr.on("data", (d) => (out += d));
    c.on("close", (code) => resolve({ code: code ?? -1, out }));
  });
}

let pass = 0;
let fail = 0;
function check(name: string, ok: boolean, detail = "") {
  if (ok) {
    pass++;
    console.log(`  ✅ ${name}`);
  } else {
    fail++;
    console.log(`  ❌ ${name} ${detail}`);
  }
}

async function main() {
  const { connectAgent, agentPreflight } = await import("../lib/infra/agent-client");
  const { SourceKind, BuildKind } = await import("../lib/agent/gen/agent");

  console.log("== preflight ==");
  const hello = await agentPreflight("srv-local");
  if (!hello.dockerAvailable) throw new Error("agent reports docker unavailable");
  check(
    "agent advertises deploy.compose.multi",
    hello.capabilities.includes("deploy.compose.multi"),
    hello.capabilities.join(","),
  );

  // The rendered stack joins the external `deplo` network; ensure it exists (the
  // agent's deploy path ensures it too, but the stack `networks: external` needs
  // it present at compose-up time).
  await sh("docker", ["network", "create", "deplo"]);

  // Two services: `web` reads an interpolated ${GREETING} from the --env-file and
  // bind-mounts a template config file the control plane carries as a mount.
  // `side` is a second service so this is genuinely multi-service. Both must come
  // up labelled with deplo.slug for the stack to be discoverable.
  const composeYaml = `# Generated by Deplo  ${SLUG}
services:
  web:
    image: busybox:latest
    command: ["sh","-c","cat /etc/deplo-msg.txt > /tmp/out; echo \\"greeting=\${GREETING}\\" >> /tmp/out; while true; do sleep 1; done"]
    volumes:
      - ${join(DATA, "stacks", "files", SLUG)}/deplo-msg.txt:/etc/deplo-msg.txt:ro
    labels:
      deplo.managed: "true"
      deplo.project: "${PROJECT_ID}"
      deplo.slug: "${SLUG}"
    networks:
      - deplo
  side:
    image: busybox:latest
    command: ["sh","-c","while true; do sleep 1; done"]
    labels:
      deplo.managed: "true"
      deplo.project: "${PROJECT_ID}"
      deplo.slug: "${SLUG}"
    networks:
      - deplo
networks:
  deplo:
    external: true
`;

  console.log("== deploy multi-service compose stack ==");
  let ready = false;
  {
    const conn = await connectAgent("srv-local");
    try {
      for await (const ev of conn.deploy({
        deployId: "dpl_compose_e2e",
        slug: SLUG,
        projectId: PROJECT_ID,
        imageRef: "", // a compose stack has no single image_ref
        sourceKind: SourceKind.SOURCE_KIND_COMPOSE,
        buildKind: BuildKind.BUILD_KIND_NONE,
        dockerfile: undefined,
        composeYaml,
        env: { GREETING: "hello-from-env-file" },
        readyTimeoutMs: 90000,
        contextTar: new Uint8Array(0),
        pullImage: false,
        mounts: [{ path: "deplo-msg.txt", content: "MOUNTED_OK\n" }],
        devWorkspaceSubdir: "",
      })) {
        if (ev.log) console.log(`  [${ev.log.level}] ${ev.log.text}`);
        if (ev.result) {
          if (!ev.result.ready) throw new Error("deploy failed: " + ev.result.error);
          ready = true;
        }
      }
    } finally {
      conn.close();
    }
  }
  check("agent reports the stack ready", ready);

  // Both services run, discoverable by the deplo.slug label (NOT by a
  // deplo-<slug> container name — the whole point of the label-based wait).
  const ids = (
    await sh("docker", ["ps", "-q", "--filter", `label=deplo.slug=${SLUG}`, "--filter", "status=running"])
  ).out.trim().split("\n").filter(Boolean);
  check("both services are running and labelled deplo.slug", ids.length === 2, `count=${ids.length}`);

  // The mount file the control plane carried was materialised AND bind-mounted in.
  const webName = (
    await sh("docker", ["ps", "--filter", `label=deplo.slug=${SLUG}`, "--format", "{{.Names}}"])
  ).out.split("\n").map((s) => s.trim()).find((n) => n.includes("web"));
  check("found the web container", Boolean(webName), webName ?? "(none)");
  if (webName) {
    const out = (await sh("docker", ["exec", webName, "cat", "/tmp/out"])).out;
    check("bind-mounted template file is present in the container", out.includes("MOUNTED_OK"), out);
    check("env-file ${VAR} was interpolated by compose", out.includes("greeting=hello-from-env-file"), out);
  }

  // Lifecycle: stop/start/destroy route through the agent and work for the stack
  // because the agent wrote <stackDir>/<slug>.yml on deploy.
  {
    const conn = await connectAgent("srv-local");
    try {
      const stop = await conn.stopStack(SLUG);
      check("StopStack ok", stop.ok, stop.error);
      const start = await conn.startStack(SLUG);
      check("StartStack ok", start.ok, start.error);
      const destroy = await conn.destroyStack(SLUG);
      check("DestroyStack ok", destroy.ok, destroy.error);
    } finally {
      conn.close();
    }
  }
  const afterDestroy = (
    await sh("docker", ["ps", "-aq", "--filter", `label=deplo.slug=${SLUG}`])
  ).out.trim();
  check("destroy removed every service", afterDestroy === "", afterDestroy);

  // Teardown.
  await sh("docker", ["compose", "-p", COMPOSE_PROJECT, "down", "--remove-orphans"]);
  rmSync(DATA, { recursive: true, force: true });
  killLocalAgent();

  console.log(`\nCompose E2E: ${pass} passed, ${fail} failed`);
  process.exit(fail === 0 ? 0 : 1);
}

function killLocalAgent(): void {
  try {
    const key = Symbol.for("deplo.localAgent.supervisor");
    const st = (globalThis as Record<symbol, unknown>)[key] as
      | { proc?: { kill?: (s?: string) => void } | null }
      | undefined;
    st?.proc?.kill?.("SIGKILL");
  } catch {
    /* best-effort */
  }
}

main().catch((e) => {
  console.error("E2E ERROR:", e);
  killLocalAgent();
  process.exit(1);
});
