import "server-only";

import yaml from "../../yaml";

import { keepAuthoredEnvText } from "../compose-lint/document";
import { mergeResourceLimits } from "../resources";
import { injectAppVolumes, rewriteAppVolumes } from "./app-volumes";
import { wireDomainRoutes } from "./domain-routers";
import {
  assertHostnameIsWritten,
  assertNetworkModeIsNotANetwork,
  collapseOntoStackNetwork,
  createAppWiring,
  joinEveryService,
} from "./stack-network";
import {
  deploLabels,
  mergeBuildLabels,
  mergeEnvironment,
  mergeLabels,
  stripTraefikLabels,
} from "./service-stamp";
import type { App, ComposeDoc, ComposeStackInput } from "./types";

function readComposeKeepingEnvText(compose: string): string {
  try {
    const doc = yaml.parseDocument(compose);
    if (doc.errors.length > 0) return compose;
    return keepAuthoredEnvText(doc) ? String(doc) : compose;
  } catch {
    return compose;
  }
}

export function buildComposeStack(input: ComposeStackInput): string {
  const { compose, name, deployKey, appId } = input;
  const trackingId = input.trackingId ?? appId;
  const envKeys = input.envKeys ?? [];
  const basicAuth = input.basicAuthUsers
    ? { name: `${name}-basicauth`, users: input.basicAuthUsers }
    : undefined;

  let doc: ComposeDoc;
  try {
    doc = (yaml.load(readComposeKeepingEnvText(compose)) as ComposeDoc) ?? {};
  } catch (e) {
    throw new Error(
      `Invalid docker-compose file: ${e instanceof Error ? e.message : String(e)}`,
    );
  }
  if (!doc.services || typeof doc.services !== "object") {
    throw new Error("Compose file has no services to deploy");
  }

  delete doc.version;

  const services = doc.services;

  const tracking = [
    ...deploLabels(trackingId, deployKey),
    ...(trackingId === appId ? [] : [`deplo.app=${appId}`]),
  ];
  const containerLabels = [...tracking, "traefik.enable=false"];
  for (const [serviceName, svc] of Object.entries(services)) {
    if (svc && typeof svc === "object") {
      assertNetworkModeIsNotANetwork(serviceName, (svc as App).network_mode);
      assertHostnameIsWritten(serviceName, (svc as App).hostname);
      delete (svc as App).container_name;
      if (input.stripPublishedPorts) delete (svc as App).ports;
      if (input.filesDir) rewriteAppVolumes(svc as App, input.filesDir);
      stripTraefikLabels(svc as App);
      mergeLabels(svc as App, containerLabels);
      mergeBuildLabels(svc as App, serviceName, tracking);
      mergeEnvironment(svc as App, envKeys);
      mergeResourceLimits(svc as App, input.resources);
    }
  }

  const wireApp = createAppWiring(services);
  wireDomainRoutes({ services, input, basicAuth, wireApp });
  joinEveryService({ doc, services, input, wireApp });
  collapseOntoStackNetwork(doc, services, input.network);

  injectAppVolumes(doc, services, input);

  const body = yaml.dump(doc, { lineWidth: -1, noRefs: true });
  return `# Generated by Deplo  ${deployKey}\n${body}`;
}
