import pg from "pg"; import fs from "node:fs"; import crypto from "node:crypto";
const env = Object.fromEntries(fs.readFileSync(".env","utf8").split("\n").filter(l=>l.includes("=")&&!l.trim().startsWith("#")).map(l=>{const i=l.indexOf("=");return [l.slice(0,i).trim(), l.slice(i+1).trim().replace(/^["']|["']$/g,"")];}));
const c = new pg.Client({connectionString: env.DEPLO_DATABASE_URL}); await c.connect();
const [teamId, userId, name] = process.argv.slice(2);
const raw = "deplo_" + crypto.randomBytes(24).toString("base64url").slice(0,32);
const hash = crypto.createHash("sha256").update(raw).digest("hex");
const id = "tok_" + crypto.randomBytes(8).toString("hex");
await c.query(`insert into api_tokens (id,team_id,user_id,name,token_hash,prefix,created_at,instance_admin,scoped,expires_at) values ($1,$2,$3,$4,$5,$6,now(),true,false,null)`,[id,teamId,userId,name,hash,raw.slice(0,12)]);
console.log(raw);
await c.end();
